# Core shell and developer utilities
brew "bash"
brew "bat"
brew "coreutils"
brew "curl"
brew "eza"
brew "fd"
brew "fzf"
brew "git"
brew "git-delta"
brew "git-lfs"
brew "gnupg"
brew "httpie"
brew "jq"
brew "make"
brew "mkcert"
brew "nmap"
brew "openssl@3"
brew "ripgrep"
brew "shellcheck"
brew "sops"
brew "starship"
brew "tmux"
brew "tree"
brew "watch"
brew "wget"
brew "yq"
brew "zoxide"

# Languages and package managers
brew "fnm"
brew "php"
brew "composer"
brew "python"
brew "pipx"
brew "uv"
brew "ruff"

# GitHub, cloud, infrastructure, and security
tap "hashicorp/tap"
brew "gh"
brew "awscli"
brew "aws-vault"
brew "hashicorp/tap/terraform"
brew "tflint"
brew "trivy"

# API, container, and data clients (servers are in Brewfile.data)
brew "kcat"
brew "mysql-client"
brew "redis"
